cpu:
  svd: STM32F429.svd
  vector_table: 0x08000000
regions:
  - name: NULL_forgiveness
    start: 0x00000000
    size: 4096
  - name: ROM
    start: 0x08000000
    load: flash.bin
    size: 0x80000
  - name: RAM-CCM
    start: 0x10000000
    size: 0x18000
  - name: RAM
    start: 0x20000000
    size: 0x30000
framebuffers:
  - name: LCD
    width: 240
    height: 320
    mode: rgb565
    sdl: true
devices:
  usart_probe:
    - peripheral: USART1
  lcd:
    - peripheral: LTDC
      framebuffer: LCD
patches:
